### MARKET EXPRESS

#### Instalación de librerias y conexión con mysql

In [1]:
!pip install python-dotenv sqlalchemy 
!pip install cryptography

Requirement already satisfied: python-dotenv in c:\users\antoo\anaconda3\envs\unicornenv\lib\site-packages (1.2.2)
Requirement already satisfied: sqlalchemy in c:\users\antoo\anaconda3\envs\unicornenv\lib\site-packages (2.0.48)
Requirement already satisfied: greenlet>=1 in c:\users\antoo\anaconda3\envs\unicornenv\lib\site-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\antoo\anaconda3\envs\unicornenv\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: cryptography in c:\users\antoo\anaconda3\envs\unicornenv\lib\site-packages (46.0.7)
Requirement already satisfied: cffi>=2.0.0 in c:\users\antoo\anaconda3\envs\unicornenv\lib\site-packages (from cryptography) (2.0.0)
Requirement already satisfied: pycparser in c:\users\antoo\anaconda3\envs\unicornenv\lib\site-packages (from cffi>=2.0.0->cryptography) (2.23)

In [2]:
import os
from dotenv import load_dotenv

load_dotenv() 

usuario = os.getenv('DB_USER')
clave = os.getenv('DB_PASS')
host = os.getenv('DB_HOST')
base_datos = os.getenv('DB_NAME')
puerto = os.getenv('DB_PORT')

In [3]:
from sqlalchemy import create_engine

engine = create_engine(f"mysql+pymysql://{usuario}:{clave}@{host}:{puerto}/{base_datos}")

In [4]:
import pandas as pd
import numpy as np

#### Creación de dataframes

In [5]:
with engine.connect() as connection:
    df_city = pd.read_sql("SELECT * FROM city", connection)
    df_country = pd.read_sql("SELECT * FROM country", connection)
    df_cl = pd.read_sql("SELECT * FROM countrylanguage", connection)

#### Exploración de dataframes

1. DF_CITY

In [6]:
df_city

        ID            Name CountryCode       District  Population
0        1           Kabul         AFG          Kabol     1780000
1        2        Qandahar         AFG       Qandahar      237500
2        3           Herat         AFG          Herat      186800
3        4  Mazar-e-Sharif         AFG          Balkh      127800
4        5       Amsterdam         NLD  Noord-Holland      731200
...    ...             ...         ...            ...         ...
4074  4075      Khan Yunis         PSE     Khan Yunis      123175
4075  4076          Hebron         PSE         Hebron      119401
4076  4077        Jabaliya         PSE     North Gaza      113901
4077  4078          Nablus         PSE         Nablus      100231
4078  4079           Rafah         PSE          Rafah       92020

[4079 rows x 5 columns]

In [7]:
df_city.info() ##no hay nulos

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4079 entries, 0 to 4078
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID           4079 non-null   int64
 1   Name         4079 non-null   object
 2   CountryCode  4079 non-null   object
 3   District     4079 non-null   object
 4   Population   4079 non-null   int64
dtypes: int64(2), object(3)
memory usage: 159.5+ KB

In [8]:
df_city.Population.describe().round(2) ##Solo Population puede analizarse numericamente

count        4079.00
mean       350468.22
std        723775.71
min            42.00
25%        114789.00
50%        167051.00
75%        310638.50
max      10500000.00
Name: Population, dtype: float64

2. DF_COUNTRY

In [9]:
df_country

,Code,Name,Continent,Region,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2
0,ABW,Aruba,North America,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Beatrix,129.0,AW
1,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
2,AGO,Angola,Africa,Central Africa,1246700.0,1975.0,12878000,38.3,6648.0,7984.0,Angola,Republic,José Eduardo dos Santos,56.0,AO
3,AIA,Anguilla,North America,Caribbean,96.0,NaN,8000,76.1,63.2,NaN,Anguilla,Dependent Territory of the UK,Elisabeth II,62.0,AI
4,ALB,Albania,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqipëria,Republic,Rexhep Mejdani,34.0,AL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,YEM,Yemen,Asia,Middle East,527968.0,1918.0,18112000,59.8,6041.0,5729.0,Al-Yaman,Republic,Ali Abdallah Salih,1780.0,YE
235,YUG,Yugoslavia,Europe,Southern Europe,102173.0,1918.0,10640000,72.4,17000.0,NaN,Jugoslavija,Federal Republic,Vojislav Koštunica,1792.0,YU
236,ZAF,South Africa,Africa,Southern Africa,1221037.0,1910.0,40377000,51.1,116729.0,129092.0,South Africa,Republic,Thabo Mbeki,716.0,ZA
237,ZMB,Zambia,Africa,Eastern Africa,752618.0,1964.0,9169000,37.2,3377.0,3922.0,Zambia,Republic,Frederick Chiluba,3162.0,ZM
238,ZWE,Zimbabwe,Africa,Eastern Africa,390757.0,1980.0,11669000,37.8,5951.0,8670.0,Zimbabwe,Republic,Robert G. Mugabe,4068.0,ZW

In [10]:
df_country.info() ## nulos en LifeExpectancy y GNPOld

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 239 entries, 0 to 238
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Code            239 non-null    object
 1   Name            239 non-null    object
 2   Continent       239 non-null    object
 3   Region          239 non-null    object
 4   SurfaceArea     239 non-null    float64
 5   IndepYear       192 non-null    float64
 6   Population      239 non-null    int64
 7   LifeExpectancy  222 non-null    float64
 8   GNP             239 non-null    float64
 9   GNPOld          178 non-null    float64
 10  LocalName       239 non-null    object
 11  GovernmentForm  239 non-null    object
 12  HeadOfState     238 non-null    object
 13  Capital         232 non-null    float64
 14  Code2           239 non-null    object
dtypes: float64(6), int64(1), object(8)
memory usage: 28.1+ KB

In [11]:
df_country2= df_country.copy()

In [12]:
df_country2

,Code,Name,Continent,Region,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2
0,ABW,Aruba,North America,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Beatrix,129.0,AW
1,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
2,AGO,Angola,Africa,Central Africa,1246700.0,1975.0,12878000,38.3,6648.0,7984.0,Angola,Republic,José Eduardo dos Santos,56.0,AO
3,AIA,Anguilla,North America,Caribbean,96.0,NaN,8000,76.1,63.2,NaN,Anguilla,Dependent Territory of the UK,Elisabeth II,62.0,AI
4,ALB,Albania,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqipëria,Republic,Rexhep Mejdani,34.0,AL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,YEM,Yemen,Asia,Middle East,527968.0,1918.0,18112000,59.8,6041.0,5729.0,Al-Yaman,Republic,Ali Abdallah Salih,1780.0,YE
235,YUG,Yugoslavia,Europe,Southern Europe,102173.0,1918.0,10640000,72.4,17000.0,NaN,Jugoslavija,Federal Republic,Vojislav Koštunica,1792.0,YU
236,ZAF,South Africa,Africa,Southern Africa,1221037.0,1910.0,40377000,51.1,116729.0,129092.0,South Africa,Republic,Thabo Mbeki,716.0,ZA
237,ZMB,Zambia,Africa,Eastern Africa,752618.0,1964.0,9169000,37.2,3377.0,3922.0,Zambia,Republic,Frederick Chiluba,3162.0,ZM
238,ZWE,Zimbabwe,Africa,Eastern Africa,390757.0,1980.0,11669000,37.8,5951.0,8670.0,Zimbabwe,Republic,Robert G. Mugabe,4068.0,ZW

#### Tratamiento de Nulos

In [13]:
df_country2['LifeExpectancy']= df_country2['LifeExpectancy'].fillna(np.mean(df_country2['LifeExpectancy'])) ## relleno nulos con la media de LifeExpectancy

In [14]:
df_country2['GNPOld']= df_country2['GNPOld'].fillna(df_country2['GNP']) ## relleno nulos con su respectivo valor de GNP

In [15]:
df_country2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 239 entries, 0 to 238
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Code            239 non-null    object
 1   Name            239 non-null    object
 2   Continent       239 non-null    object
 3   Region          239 non-null    object
 4   SurfaceArea     239 non-null    float64
 5   IndepYear       192 non-null    float64
 6   Population      239 non-null    int64
 7   LifeExpectancy  239 non-null    float64
 8   GNP             239 non-null    float64
 9   GNPOld          239 non-null    float64
 10  LocalName       239 non-null    object
 11  GovernmentForm  239 non-null    object
 12  HeadOfState     238 non-null    object
 13  Capital         232 non-null    float64
 14  Code2           239 non-null    object
dtypes: float64(6), int64(1), object(8)
memory usage: 28.1+ KB

In [16]:
df_country2[['SurfaceArea', 'Population', 'LifeExpectancy', 'GNP', 'GNPOld']].describe().round(2)

       SurfaceArea    Population  LifeExpectancy         GNP      GNPOld
count       239.00  2.390000e+02          239.00      239.00      239.00
mean     623248.15  2.543410e+07           66.49   122823.88   123659.92
std     1924139.85  1.093398e+08           11.10   637997.58   625440.84
min           0.40  0.000000e+00           37.20        0.00        0.00
25%        2275.00  2.380000e+05           61.65      640.00      648.50
50%       71740.00  3.869000e+06           69.20     4787.00     4361.00
75%      398754.50  1.493550e+07           75.15    29944.50    31169.50
max    17075400.00  1.277558e+09           83.50  8510700.00  8110900.00

3. DF_CL

In [17]:
df_cl

    CountryCode    Language IsOfficial  Percentage
0           ABW       Dutch          T         5.3
1           ABW     English          F         9.5
2           ABW  Papiamento          F        76.7
3           ABW     Spanish          F         7.4
4           AFG     Balochi          F         0.9
..          ...         ...        ...         ...
979         ZMB       Tonga          F        11.0
980         ZWE     English          T         2.2
981         ZWE     Ndebele          F        16.2
982         ZWE      Nyanja          F         2.2
983         ZWE       Shona          F        72.1

[984 rows x 4 columns]

In [18]:
df_cl.info() ## no contiene nulos

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 984 entries, 0 to 983
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CountryCode  984 non-null    object
 1   Language     984 non-null    object
 2   IsOfficial   984 non-null    object
 3   Percentage   984 non-null    float64
dtypes: float64(1), object(3)
memory usage: 30.9+ KB

In [19]:
df_cl.describe()

       Percentage
count  984.000000
mean    20.374390
std     30.829452
min      0.000000
25%      1.275000
50%      5.300000
75%     21.125000
max    100.000000

#### Creación de columnas calculadas necesarias para el análisis

- Crecimiento_económico GNP>GNPOld
- GNP_per_cápita  GNP/Población del país
- Densidad_poblacional Población del país/Superficie

In [20]:
df_country2['Crecimiento_económico']= np.where(df_country2['GNP'] > df_country2['GNPOld'], 'Si', 'No')

In [21]:
df_country2['GNP_per_cápita']= ((df_country2['GNP'] * 1000000) / df_country2['Population']).round(2)

In [22]:
df_country2['Densidad_poblacional']= (df_country2['Population'] / df_country2['SurfaceArea']).round(2)

In [23]:
df_country2.head()

,Code,Name,Continent,Region,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2,Crecimiento_económico,GNP_per_cápita,Densidad_poblacional
0,ABW,Aruba,North America,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Beatrix,129.0,AW,Si,8038.83,533.68
1,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,5976.0,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF,No,263.03,34.84
2,AGO,Angola,Africa,Central Africa,1246700.0,1975.0,12878000,38.3,6648.0,7984.0,Angola,Republic,José Eduardo dos Santos,56.0,AO,No,516.23,10.33
3,AIA,Anguilla,North America,Caribbean,96.0,NaN,8000,76.1,63.2,63.2,Anguilla,Dependent Territory of the UK,Elisabeth II,62.0,AI,No,7900.00,83.33
4,ALB,Albania,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqipëria,Republic,Rexhep Mejdani,34.0,AL,Si,942.31,118.31

#### Análisis población

In [24]:
df_country2.loc[df_country2['Code'] == 'CHN', 'Population'] = 1500000000 ## Consigna 5 - Actualizo el valor de population de china

In [25]:
df_country2[['Name', 'Population']].sort_values(by='Population', ascending=False)

                                             Name  Population
41                                          China  1500000000
99                                          India  1013662000
223                                 United States   278357000
98                                      Indonesia   212107000
30                                         Brazil   170115000
..                                            ...         ...
34                                  Bouvet Island           0
12                    French Southern territories           0
93              Heard Island and McDonald Islands           0
187  South Georgia and the South Sandwich Islands           0
221          United States Minor Outlying Islands           0

[239 rows x 2 columns]

In [26]:
df_country2.nlargest(10,'Population')[['Name', 'Population']]

                   Name  Population
41                China  1500000000
99                India  1013662000
223       United States   278357000
98            Indonesia   212107000
30               Brazil   170115000
164            Pakistan   156483000
181  Russian Federation   146934000
21           Bangladesh   129155000
109               Japan   126714000
155             Nigeria   111506000

In [27]:
df_country2[['Name', 'Population']][df_country2['Continent']== 'Europe'] ##Consigna 1

                              Name  Population
4                          Albania     3401200
5                          Andorra       78000
15                         Austria     8091800
18                         Belgium    10239000
22                        Bulgaria     8190900
25          Bosnia and Herzegovina     3972000
26                         Belarus    10236000
39                     Switzerland     7160400
55                  Czech Republic    10278100
56                         Germany    82164700
59                         Denmark     5330000
66                           Spain    39441700
67                         Estonia     1439200
69                         Finland     5171300
72                          France    59225700
73                   Faroe Islands       43000
76                  United Kingdom    59623400
79                       Gibraltar       25000
85                          Greece    10545700
95                         Croatia     4473000
97                         Hungary    10043200
101                        Ireland     3775100
104                        Iceland      279000
106                          Italy    57680000
123                  Liechtenstein       32300
126                      Lithuania     3698500
127                     Luxembourg      435700
128                         Latvia     2424200
131                         Monaco       34000
132                        Moldova     4380000
137                      Macedonia     2024000
139                          Malta      380200
158                    Netherlands    15864000
159                         Norway     4478500
171                         Poland    38653600
174                       Portugal     9997600
180                        Romania    22455500
181             Russian Federation   146934000
189         Svalbard and Jan Mayen        3200
193                     San Marino       27000
198                       Slovakia     5398700
199                       Slovenia     1987800
200                         Sweden     8861400
220                        Ukraine    50456000
225  Holy See (Vatican City State)        1000
235                     Yugoslavia    10640000

In [28]:
df_country2.Continent.unique()

array(['North America', 'Asia', 'Africa', 'Europe', 'South America',
       'Oceania', 'Antarctica'], dtype=object)

In [29]:
df_country2['Continent'] = df_country2['Continent'].apply(lambda x: 'America' if x in ['North America', 'South America'] else x) ##Cambio North America y South America a America

In [30]:
df_country2[['Name', 'Population']][df_country2['Continent']== 'America']

                                 Name  Population
0                               Aruba      103000
3                            Anguilla        8000
6                Netherlands Antilles      217000
8                           Argentina    37032000
13                Antigua and Barbuda       68000
24                            Bahamas      307000
27                             Belize      241000
28                            Bermuda       65000
29                            Bolivia     8329000
30                             Brazil   170115000
31                           Barbados      270000
37                             Canada    31147000
40                              Chile    15211000
47                           Colombia    42321000
50                         Costa Rica     4023000
51                               Cuba    11201000
53                     Cayman Islands       38000
58                           Dominica       71000
60                 Dominican Republic     8495000
62                            Ecuador    12646000
71                   Falkland Islands        2000
81                         Guadeloupe      456000
86                            Grenada       94000
87                          Greenland       56000
88                          Guatemala    11385000
89                      French Guiana      181000
91                             Guyana      861000
94                           Honduras     6485000
96                              Haiti     8222000
107                           Jamaica     2583000
115             Saint Kitts and Nevis       38000
122                       Saint Lucia      154000
135                            Mexico    98881000
145                        Montserrat       11000
146                        Martinique      395000
156                         Nicaragua     5074000
165                            Panama     2856000
167                              Peru    25662000
172                       Puerto Rico     3869000
175                          Paraguay     5496000
192                       El Salvador     6276000
195         Saint Pierre and Miquelon        7000
197                          Suriname      417000
204          Turks and Caicos Islands       17000
213               Trinidad and Tobago     1295000
222                           Uruguay     3337000
223                     United States   278357000
226  Saint Vincent and the Grenadines      114000
227                         Venezuela    24170000
228           Virgin Islands, British       21000
229              Virgin Islands, U.S.       93000

In [31]:
df_country2[['Name', 'Population']][df_country2['Continent']== 'Asia']

                     Name  Population
1             Afghanistan    22720000
7    United Arab Emirates     2441000
9                 Armenia     3520000
16             Azerbaijan     7734000
21             Bangladesh   129155000
23                Bahrain      617000
32                 Brunei      328000
33                 Bhutan     2124000
41                  China  1500000000
54                 Cyprus      754700
77                Georgia     4968000
92              Hong Kong     6782000
98              Indonesia   212107000
99                  India  1013662000
102                  Iran    67702000
103                  Iraq    23115000
105                Israel     6217000
108                Jordan     5083000
109                 Japan   126714000
110             Kazakstan    16223000
112            Kyrgyzstan     4699000
113              Cambodia    11168000
116           South Korea    46844000
117                Kuwait     1972000
118                  Laos     5433000
119               Lebanon     3282000
124             Sri Lanka    18827000
129                 Macao      473000
134              Maldives      286000
140               Myanmar    45611000
141              Mongolia     2662000
149              Malaysia    22244000
160                 Nepal    23930000
163                  Oman     2542000
164              Pakistan   156483000
168           Philippines    75967000
173           North Korea    24039000
176             Palestine     3101000
178                 Qatar      599000
183          Saudi Arabia    21607000
186             Singapore     3567000
203                 Syria    16125000
207              Thailand    61399000
208            Tajikistan     6188000
210          Turkmenistan     4459000
211            East Timor      885000
215                Turkey    66591000
217                Taiwan    22256000
224            Uzbekistan    24318000
230               Vietnam    79832000
234                 Yemen    18112000

In [32]:
df_country2[['Name', 'Population']][df_country2['Continent']== 'Oceania']

                                     Name  Population
10                         American Samoa       68000
14                              Australia    18886000
38                Cocos (Keeling) Islands         600
46                           Cook Islands       20000
52                       Christmas Island        2500
70                           Fiji Islands      817000
74        Micronesia, Federated States of      119000
90                                   Guam      168000
114                              Kiribati       83000
136                      Marshall Islands       64000
142              Northern Mariana Islands       78000
152                         New Caledonia      214000
154                        Norfolk Island        2000
157                                  Niue        2000
161                                 Nauru       12000
162                           New Zealand     3862000
166                              Pitcairn          50
169                                 Palau       19000
170                      Papua New Guinea     4807000
177                      French Polynesia      235000
190                       Solomon Islands      444000
209                               Tokelau        2000
212                                 Tonga       99000
216                                Tuvalu       12000
221  United States Minor Outlying Islands           0
231                               Vanuatu      190000
232                     Wallis and Futuna       15000
233                                 Samoa      180000

In [33]:
df_country2[['Name', 'Population']][df_country2['Continent']== 'Africa']

                                      Name  Population
2                                   Angola    12878000
17                                 Burundi     6695000
19                                   Benin     6097000
20                            Burkina Faso    11937000
35                                Botswana     1622000
36                Central African Republic     3615000
42                           Côte d’Ivoire    14786000
43                                Cameroon    15085000
44   Congo, The Democratic Republic of the    51654000
45                                   Congo     2943000
48                                 Comoros      578000
49                              Cape Verde      428000
57                                Djibouti      638000
61                                 Algeria    31471000
63                                   Egypt    68470000
64                                 Eritrea     3850000
65                          Western Sahara      293000
68                                Ethiopia    62565000
75                                   Gabon     1226000
78                                   Ghana    20212000
80                                  Guinea     7430000
82                                  Gambia     1305000
83                           Guinea-Bissau     1213000
84                       Equatorial Guinea      453000
100         British Indian Ocean Territory           0
111                                  Kenya    30080000
120                                Liberia     3154000
121                 Libyan Arab Jamahiriya     5605000
125                                Lesotho     2153000
130                                Morocco    28351000
133                             Madagascar    15942000
138                                   Mali    11234000
143                             Mozambique    19680000
144                             Mauritania     2670000
147                              Mauritius     1158000
148                                 Malawi    10925000
150                                Mayotte      149000
151                                Namibia     1726000
153                                  Niger    10730000
155                                Nigeria   111506000
179                                Réunion      699000
182                                 Rwanda     7733000
184                                  Sudan    29490000
185                                Senegal     9481000
188                           Saint Helena        6000
191                           Sierra Leone     4854000
194                                Somalia    10097000
196                  Sao Tome and Principe      147000
201                              Swaziland     1008000
202                             Seychelles       77000
205                                   Chad     7651000
206                                   Togo     4629000
214                                Tunisia     9586000
218                               Tanzania    33517000
219                                 Uganda    21778000
236                           South Africa    40377000
237                                 Zambia     9169000
238                               Zimbabwe    11669000

In [34]:
df_country2[['Name', 'Population']][df_country2['Continent']== 'Antarctica'] ## Tiene población 0

                                             Name  Population
11                                     Antarctica           0
12                    French Southern territories           0
34                                  Bouvet Island           0
93              Heard Island and McDonald Islands           0
187  South Georgia and the South Sandwich Islands           0

In [35]:
df_country2.groupby('Continent').agg({'Population':'sum'}) ## Consigna 3 - opción de solo continentes y suma total de población

            Population
Continent
Africa       784475000
America      828773000
Antarctica           0
Asia        3927467700
Europe       730074600
Oceania       30401150

In [36]:
df_country2.groupby(['Continent','Name']).agg({'Population':'sum'}) ## Consigna 3 - opción de continentes y paises con su población total

                                                Population
Continent Name
Africa    Algeria                                 31471000
          Angola                                  12878000
          Benin                                    6097000
          Botswana                                 1622000
          British Indian Ocean Territory                 0
...                                                    ...
Oceania   Tonga                                      99000
          Tuvalu                                     12000
          United States Minor Outlying Islands           0
          Vanuatu                                   190000
          Wallis and Futuna                          15000

[239 rows x 1 columns]

In [37]:
df_join = pd.merge(df_city, df_country, left_on='CountryCode', right_on='Code') ## Consigna 4 ciuades y su población por país

In [38]:
df_join

,ID,Name_x,CountryCode,District,Population_x,Code,Name_y,Continent,Region,SurfaceArea,IndepYear,Population_y,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2
0,1,Kabul,AFG,Kabol,1780000,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
1,2,Qandahar,AFG,Qandahar,237500,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
2,3,Herat,AFG,Herat,186800,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
3,4,Mazar-e-Sharif,AFG,Balkh,127800,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
4,5,Amsterdam,NLD,Noord-Holland,731200,NLD,Netherlands,Europe,Western Europe,41526.0,1581.0,15864000,78.3,371362.0,360478.0,Nederland,Constitutional Monarchy,Beatrix,5.0,NL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4074,4075,Khan Yunis,PSE,Khan Yunis,123175,PSE,Palestine,Asia,Middle East,6257.0,NaN,3101000,71.4,4173.0,NaN,Filastin,Autonomous Area,Yasser (Yasir) Arafat,4074.0,PS
4075,4076,Hebron,PSE,Hebron,119401,PSE,Palestine,Asia,Middle East,6257.0,NaN,3101000,71.4,4173.0,NaN,Filastin,Autonomous Area,Yasser (Yasir) Arafat,4074.0,PS
4076,4077,Jabaliya,PSE,North Gaza,113901,PSE,Palestine,Asia,Middle East,6257.0,NaN,3101000,71.4,4173.0,NaN,Filastin,Autonomous Area,Yasser (Yasir) Arafat,4074.0,PS
4077,4078,Nablus,PSE,Nablus,100231,PSE,Palestine,Asia,Middle East,6257.0,NaN,3101000,71.4,4173.0,NaN,Filastin,Autonomous Area,Yasser (Yasir) Arafat,4074.0,PS
4078,4079,Rafah,PSE,Rafah,92020,PSE,Palestine,Asia,Middle East,6257.0,NaN,3101000,71.4,4173.0,NaN,Filastin,Autonomous Area,Yasser (Yasir) Arafat,4074.0,PS

In [39]:
df_join = df_join.rename(columns={
    'Name_x': 'City',
    'Population_x': 'Population_city',
    'Name_y': 'Country',
    'Population_y': 'Population_country'})

In [40]:
df_join

,ID,City,CountryCode,District,Population_city,Code,Country,Continent,Region,SurfaceArea,IndepYear,Population_country,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2
0,1,Kabul,AFG,Kabol,1780000,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
1,2,Qandahar,AFG,Qandahar,237500,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
2,3,Herat,AFG,Herat,186800,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
3,4,Mazar-e-Sharif,AFG,Balkh,127800,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
4,5,Amsterdam,NLD,Noord-Holland,731200,NLD,Netherlands,Europe,Western Europe,41526.0,1581.0,15864000,78.3,371362.0,360478.0,Nederland,Constitutional Monarchy,Beatrix,5.0,NL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4074,4075,Khan Yunis,PSE,Khan Yunis,123175,PSE,Palestine,Asia,Middle East,6257.0,NaN,3101000,71.4,4173.0,NaN,Filastin,Autonomous Area,Yasser (Yasir) Arafat,4074.0,PS
4075,4076,Hebron,PSE,Hebron,119401,PSE,Palestine,Asia,Middle East,6257.0,NaN,3101000,71.4,4173.0,NaN,Filastin,Autonomous Area,Yasser (Yasir) Arafat,4074.0,PS
4076,4077,Jabaliya,PSE,North Gaza,113901,PSE,Palestine,Asia,Middle East,6257.0,NaN,3101000,71.4,4173.0,NaN,Filastin,Autonomous Area,Yasser (Yasir) Arafat,4074.0,PS
4077,4078,Nablus,PSE,Nablus,100231,PSE,Palestine,Asia,Middle East,6257.0,NaN,3101000,71.4,4173.0,NaN,Filastin,Autonomous Area,Yasser (Yasir) Arafat,4074.0,PS
4078,4079,Rafah,PSE,Rafah,92020,PSE,Palestine,Asia,Middle East,6257.0,NaN,3101000,71.4,4173.0,NaN,Filastin,Autonomous Area,Yasser (Yasir) Arafat,4074.0,PS

In [41]:
Ciudades_europa = df_join[df_join['Continent'] == 'Europe'][['City', 'Population_city']].sort_values(by='Population_city', ascending=False)

In [42]:
Ciudades_europa

                    City  Population_city
3579              Moscow          8389200
455               London          7285000
3580       St Petersburg          4694000
3067              Berlin          3386667
652               Madrid          2879052
...                  ...              ...
3169          Serravalle             4802
3170          San Marino             2294
937         Longyearbyen             1438
2694        Monaco-Ville             1234
3537  Città del Vaticano              455

[841 rows x 2 columns]

#### Análisis Superficie

In [43]:
df_country2.nlargest(5, 'SurfaceArea')[['Name', 'SurfaceArea']] ## Consigna 2 - obtengo los 5 paises con mayor superficie

                   Name  SurfaceArea
181  Russian Federation   17075400.0
11           Antarctica   13120000.0
37               Canada    9970610.0
41                China    9572900.0
223       United States    9363520.0

In [44]:
df_country2.groupby('Continent')['SurfaceArea'].sum().sort_values(ascending=False) ##Superficie de cada continente

Continent
America       42079396.0
Asia          31881005.0
Africa        30250377.0
Europe        23049133.9
Antarctica    13132101.0
Oceania        8564294.0
Name: SurfaceArea, dtype: float64

In [45]:
df_country2['SurfaceArea'].mean().round(2) ## Superficie media de paises

np.float64(623248.15)

#### Análisis Densidad Poblacional

In [46]:
df_country2['Densidad_poblacional'].mean().round(2) ## Densidad poblacional media

np.float64(409.86)

In [47]:
df_country2.groupby('Continent')['Densidad_poblacional'].sum().sort_values(ascending=False)

Continent
Asia          47129.36
Europe        35393.39
America        7763.12
Africa         4301.91
Oceania        3368.63
Antarctica        0.00
Name: Densidad_poblacional, dtype: float64

In [48]:
df_country2[['Densidad_poblacional', 'Name']] ## Consigna 8 - Densidad poblacional por país

     Densidad_poblacional          Name
0                  533.68         Aruba
1                   34.84   Afghanistan
2                   10.33        Angola
3                   83.33      Anguilla
4                  118.31       Albania
..                    ...           ...
234                 34.31         Yemen
235                104.14    Yugoslavia
236                 33.07  South Africa
237                 12.18        Zambia
238                 29.86      Zimbabwe

[239 rows x 2 columns]

#### Análisis de Idiomas

In [49]:
df_lan_official= df_cl[df_cl['IsOfficial'] == 'T'][['CountryCode', 'Language']] ##Idioma oficial de cada pais

In [50]:
df_lan_official

    CountryCode   Language
0           ABW      Dutch
5           AFG       Dari
6           AFG     Pashto
18          AIA    English
19          ALB  Albaniana
..          ...        ...
963         ZAF  Afrikaans
964         ZAF    English
972         ZAF      Xhosa
973         ZAF       Zulu
980         ZWE    English

[238 rows x 2 columns]

In [51]:
df_cl2= pd.merge(df_join, df_cl, left_on= 'Code', right_on= 'CountryCode')

In [52]:
df_cl2

,ID,City,CountryCode_x,District,Population_city,Code,Country,Continent,Region,SurfaceArea,...,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2,CountryCode_y,Language,IsOfficial,Percentage
0,1,Kabul,AFG,Kabol,1780000,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,...,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF,AFG,Balochi,F,0.9
1,1,Kabul,AFG,Kabol,1780000,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,...,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF,AFG,Dari,T,32.1
2,1,Kabul,AFG,Kabol,1780000,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,...,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF,AFG,Pashto,T,52.4
3,1,Kabul,AFG,Kabol,1780000,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,...,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF,AFG,Turkmenian,F,1.9
4,1,Kabul,AFG,Kabol,1780000,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,...,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF,AFG,Uzbek,F,8.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30665,4077,Jabaliya,PSE,North Gaza,113901,PSE,Palestine,Asia,Middle East,6257.0,...,NaN,Filastin,Autonomous Area,Yasser (Yasir) Arafat,4074.0,PS,PSE,Hebrew,F,4.1
30666,4078,Nablus,PSE,Nablus,100231,PSE,Palestine,Asia,Middle East,6257.0,...,NaN,Filastin,Autonomous Area,Yasser (Yasir) Arafat,4074.0,PS,PSE,Arabic,F,95.9
30667,4078,Nablus,PSE,Nablus,100231,PSE,Palestine,Asia,Middle East,6257.0,...,NaN,Filastin,Autonomous Area,Yasser (Yasir) Arafat,4074.0,PS,PSE,Hebrew,F,4.1
30668,4079,Rafah,PSE,Rafah,92020,PSE,Palestine,Asia,Middle East,6257.0,...,NaN,Filastin,Autonomous Area,Yasser (Yasir) Arafat,4074.0,PS,PSE,Arabic,F,95.9
30669,4079,Rafah,PSE,Rafah,92020,PSE,Palestine,Asia,Middle East,6257.0,...,NaN,Filastin,Autonomous Area,Yasser (Yasir) Arafat,4074.0,PS,PSE,Hebrew,F,4.1

In [53]:
Count_lan= df_cl2.groupby('Country')['Language'].nunique() ## Paises y recuento de idiomas, odenado de forma descendiente

In [54]:
Count_lan.sort_values(ascending=False)

Country
Canada                      12
China                       12
India                       12
United States               12
Russian Federation          12
                            ..
Saudi Arabia                 1
Turks and Caicos Islands     1
Uruguay                      1
Western Sahara               1
Virgin Islands, British      1
Name: Language, Length: 232, dtype: int64

In [55]:
Cont_lan= df_cl2.groupby('Continent')['Language'].nunique() ## Consigna 10 - Continentes y recuento de idiomas, odenado de forma descendiente

In [56]:
Cont_lan

Continent
Africa           215
Asia             138
Europe            62
North America     43
Oceania           43
South America     21
Name: Language, dtype: int64

In [57]:
df_cl2[(df_cl2['IsOfficial']== 'T') & (df_cl2['Continent'] =='South America')]['Language'].unique() ## Consigna 6, idiomas oficiales en South America

array(['Spanish', 'Aimará', 'Ketšua', 'Portuguese', 'English', 'Guaraní'],
      dtype=object)

In [58]:
df_cl2[(df_cl2['IsOfficial']== 'T') & (df_cl2['Continent'] =='South America')]['Language'].nunique()

6

In [59]:
df_cl2[(df_cl2['IsOfficial']== 'F') & (df_cl2['Continent'] =='South America')]['Language'].unique()

array(['Indian Languages', 'Italian', 'Guaraní', 'German', 'Japanese',
       'Aimará', 'Araucan', 'Rapa nui', 'Ketšua', 'Arawakan', 'Caribbean',
       'Creole English', 'Chibcha', 'Portuguese', 'Creole French',
       'Hindi', 'Sranantonga', 'Goajiro', 'Warrau'], dtype=object)

In [60]:
df_cl2[(df_cl2['IsOfficial']== 'F') & (df_cl2['Continent'] =='South America')]['Language'].nunique()

19

In [61]:
df_cl2[df_cl2['Continent'] =='South America']['Language'].nunique()

21

In [62]:
df_cl[df_cl['CountryCode']=='AGO'] ## Hay paises que no tienen idiomas oficiales

   CountryCode          Language IsOfficial  Percentage
9          AGO              Ambo          F         2.4
10         AGO            Chokwe          F         4.2
11         AGO             Kongo          F        13.2
12         AGO           Luchazi          F         2.4
13         AGO  Luimbe-nganguela          F         5.4
14         AGO            Luvale          F         3.6
15         AGO            Mbundu          F        21.6
16         AGO   Nyaneka-nkhumbi          F         5.4
17         AGO         Ovimbundu          F        37.2

In [63]:
max_index = df_cl2.groupby('Country')['Percentage'].idxmax() ##mayores porcentajes de idiomas por pais

In [64]:
df_max_lan = df_cl2.loc[max_index]

In [65]:
df_max_lan2 = df_max_lan[['Country', 'Language', 'Percentage']]

In [66]:
df_max_lan2.sort_values(by='Percentage', ascending=False)

                         Country        Language  Percentage
13375                 Cape Verde         Crioulo       100.0
816                      Bermuda         English       100.0
4899                     Grenada  Creole English       100.0
4953                       Haiti    Haiti Creole       100.0
2551                    Dominica  Creole English       100.0
...                          ...             ...         ...
22316  Saint Pierre and Miquelon          French         0.0
24083   Turks and Caicos Islands         English         0.0
23751                    Tokelau         English         0.0
24738          Wallis and Futuna          Futuna         0.0
2359     Virgin Islands, British         English         0.0

[232 rows x 3 columns]

#### Análisis Condiciones de Vida

In [67]:
df_country2[df_country2['LifeExpectancy']>75]['Name'] ## Consigna 7 - paises con LifeExpectancy >75 años

0                        Aruba
3                     Anguilla
5                      Andorra
8                    Argentina
10              American Samoa
                ...
217                     Taiwan
222                    Uruguay
223              United States
228    Virgin Islands, British
229       Virgin Islands, U.S.
Name: Name, Length: 62, dtype: object

In [68]:
df_country2[df_country2['LifeExpectancy']>75]['Name'].count()

np.int64(62)

In [69]:
df_country2['LifeExpectancy'].mean() ## LifeExpectancy media

np.float64(66.48603603603604)

In [70]:
max_esp = df_country2['LifeExpectancy'].idxmax()

In [71]:
max_esp2 = df_country2.loc[max_esp, ['Name', 'LifeExpectancy']]

In [72]:
max_esp2 ## Pais con mayor LifeExpectancy

Name              Andorra
LifeExpectancy       83.5
Name: 5, dtype: object

In [73]:
df_country2.groupby('Continent')['LifeExpectancy'].mean() ## LifeExpectancy media por continente

Continent
Africa        52.811828
America       72.342863
Antarctica    66.486036
Asia          67.441176
Europe        74.771132
Oceania       68.792439
Name: LifeExpectancy, dtype: float64

#### Análisis de GNP y GNP Per cápita

In [74]:
df_country2[df_country2['Crecimiento_económico']== 'Si'] ## Paises que tuvieron crecimiento económico

,Code,Name,Continent,Region,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2,Crecimiento_económico,GNP_per_cápita,Densidad_poblacional
0,ABW,Aruba,America,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Beatrix,129.0,AW,Si,8038.83,533.68
4,ALB,Albania,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqipëria,Republic,Rexhep Mejdani,34.0,AL,Si,942.31,118.31
7,ARE,United Arab Emirates,Asia,Middle East,83600.0,1971.0,2441000,74.1,37966.0,36846.0,Al-Imarat al-´Arabiya al-Muttahida,Emirate Federation,Zayid bin Sultan al-Nahayan,65.0,AE,Si,15553.46,29.20
8,ARG,Argentina,America,South America,2780400.0,1816.0,37032000,75.1,340238.0,323310.0,Argentina,Federal Republic,Fernando de la Rúa,69.0,AR,Si,9187.68,13.32
9,ARM,Armenia,Asia,Middle East,29800.0,1991.0,3520000,66.4,1813.0,1627.0,Hajastan,Republic,Robert Kotšarjan,126.0,AM,Si,515.06,118.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
223,USA,United States,America,North America,9363520.0,1776.0,278357000,77.1,8510700.0,8110900.0,United States,Federal Republic,George W. Bush,3813.0,US,Si,30574.77,29.73
227,VEN,Venezuela,America,South America,912050.0,1811.0,24170000,73.1,95023.0,88434.0,Venezuela,Federal Republic,Hugo Chávez Frías,3539.0,VE,Si,3931.44,26.50
228,VGB,"Virgin Islands, British",America,Caribbean,151.0,NaN,21000,75.4,612.0,573.0,British Virgin Islands,Dependent Territory of the UK,Elisabeth II,537.0,VG,Si,29142.86,139.07
231,VUT,Vanuatu,Oceania,Melanesia,12189.0,1980.0,190000,60.6,261.0,246.0,Vanuatu,Republic,John Bani,3537.0,VU,Si,1373.68,15.59
234,YEM,Yemen,Asia,Middle East,527968.0,1918.0,18112000,59.8,6041.0,5729.0,Al-Yaman,Republic,Ali Abdallah Salih,1780.0,YE,Si,333.54,34.31

In [75]:
df_country2[df_country2['Crecimiento_económico']== 'Si'].count() ##Cantidad de paises que tuvieron crecimiento economico

Code                     115
Name                     115
Continent                115
Region                   115
SurfaceArea              115
IndepYear                106
Population               115
LifeExpectancy           115
GNP                      115
GNPOld                   115
LocalName                115
GovernmentForm           115
HeadOfState              115
Capital                  115
Code2                    115
Crecimiento_económico    115
GNP_per_cápita           115
Densidad_poblacional     115
dtype: int64

In [76]:
df_country2[(df_country2['Crecimiento_económico']== 'Si') & (df_country2['Continent']== 'Europe')] ## Paises con crecimiento economico en Europa

,Code,Name,Continent,Region,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2,Crecimiento_económico,GNP_per_cápita,Densidad_poblacional
4,ALB,Albania,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqipëria,Republic,Rexhep Mejdani,34.0,AL,Si,942.31,118.31
15,AUT,Austria,Europe,Western Europe,83859.0,1918.0,8091800,77.7,211860.0,206025.0,Österreich,Federal Republic,Thomas Klestil,1523.0,AT,Si,26182.06,96.49
18,BEL,Belgium,Europe,Western Europe,30518.0,1830.0,10239000,77.8,249704.0,243948.0,België/Belgique,"Constitutional Monarchy, Federation",Albert II,179.0,BE,Si,24387.54,335.51
22,BGR,Bulgaria,Europe,Eastern Europe,110994.0,1908.0,8190900,70.9,12178.0,10169.0,Balgarija,Republic,Petar Stojanov,539.0,BG,Si,1486.77,73.80
39,CHE,Switzerland,Europe,Western Europe,41284.0,1499.0,7160400,79.6,264478.0,256092.0,Schweiz/Suisse/Svizzera/Svizra,Federation,Adolf Ogi,3248.0,CH,Si,36936.20,173.44
55,CZE,Czech Republic,Europe,Eastern Europe,78866.0,1993.0,10278100,74.5,55017.0,52037.0,¸esko,Republic,Václav Havel,3339.0,CZ,Si,5352.84,130.32
56,DEU,Germany,Europe,Western Europe,357022.0,1955.0,82164700,77.4,2133367.0,2102826.0,Deutschland,Federal Republic,Johannes Rau,3068.0,DE,Si,25964.52,230.14
59,DNK,Denmark,Europe,Nordic Countries,43094.0,800.0,5330000,76.5,174099.0,169264.0,Danmark,Constitutional Monarchy,Margrethe II,3315.0,DK,Si,32663.98,123.68
66,ESP,Spain,Europe,Southern Europe,505992.0,1492.0,39441700,78.8,553233.0,532031.0,España,Constitutional Monarchy,Juan Carlos I,653.0,ES,Si,14026.60,77.95
67,EST,Estonia,Europe,Baltic Countries,45227.0,1991.0,1439200,69.5,5328.0,3371.0,Eesti,Republic,Lennart Meri,3791.0,EE,Si,3702.06,31.82
69,FIN,Finland,Europe,Nordic Countries,338145.0,1917.0,5171300,77.4,121914.0,119833.0,Suomi,Republic,Tarja Halonen,3236.0,FI,Si,23575.12,15.29
72,FRA,France,Europe,Western Europe,551500.0,843.0,59225700,78.8,1424285.0,1392448.0,France,Republic,Jacques Chirac,2974.0,FR,Si,24048.43,107.39
76,GBR,United Kingdom,Europe,British Islands,242900.0,1066.0,59623400,77.7,1378330.0,1296830.0,United Kingdom,Constitutional Monarchy,Elisabeth II,456.0,GB,Si,23117.27,245.46
85,GRC,Greece,Europe,Southern Europe,131626.0,1830.0,10545700,78.4,120724.0,119946.0,Elláda,Republic,Kostis Stefanopoulos,2401.0,GR,Si,11447.70,80.12
95,HRV,Croatia,Europe,Southern Europe,56538.0,1991.0,4473000,73.7,20208.0,19300.0,Hrvatska,Republic,Štipe Mesic,2409.0,HR,Si,4517.77,79.11
97,HUN,Hungary,Europe,Eastern Europe,93030.0,1918.0,10043200,71.4,48267.0,45914.0,Magyarország,Republic,Ferenc Mádl,3483.0,HU,Si,4805.94,107.96
101,IRL,Ireland,Europe,British Islands,70273.0,1921.0,3775100,76.8,75921.0,73132.0,Ireland/Éire,Republic,Mary McAleese,1447.0,IE,Si,20110.99,53.72
104,ISL,Iceland,Europe,Nordic Countries,103000.0,1944.0,279000,79.4,8255.0,7474.0,Ísland,Republic,Ólafur Ragnar Grímsson,1449.0,IS,Si,29587.81,2.71
106,ITA,Italy,Europe,Southern Europe,301316.0,1861.0,57680000,79.0,1161755.0,1145372.0,Italia,Republic,Carlo Azeglio Ciampi,1464.0,IT,Si,20141.38,191.43
123,LIE,Liechtenstein,Europe,Western Europe,160.0,1806.0,32300,78.8,1119.0,1084.0,Liechtenstein,Constitutional Monarchy,Hans-Adam II,2446.0,LI,Si,34643.96,201.88
126,LTU,Lithuania,Europe,Baltic Countries,65301.0,1991.0,3698500,69.1,10692.0,9585.0,Lietuva,Republic,Valdas Adamkus,2447.0,LT,Si,2890.90,56.64
127,LUX,Luxembourg,Europe,Western Europe,2586.0,1867.0,435700,77.1,16321.0,15519.0,Luxembourg/Lëtzebuerg,Constitutional Monarchy,Henri,2452.0,LU,Si,37459.26,168.48
128,LVA,Latvia,Europe,Baltic Countries,64589.0,1991.0,2424200,68.4,6398.0,5639.0,Latvija,Republic,Vaira Vike-Freiberga,2434.0,LV,Si,2639.22,37.53
139,MLT,Malta,Europe,Southern Europe,316.0,1964.0,380200,77.9,3512.0,3338.0,Malta,Republic,Guido de Marco,2484.0,MT,Si,9237.24,1203.16
158,NLD,Netherlands,Europe,Western Europe,41526.0,1581.0,15864000,78.3,371362.0,360478.0,Nederland,Constitutional Monarchy,Beatrix,5.0,NL,Si,23409.10,382.03
171,POL,Poland,Europe,Eastern Europe,323250.0,1918.0,38653600,73.2,151697.0,135636.0,Polska,Republic,Aleksander Kwasniewski,2928.0,PL,Si,3924.52,119.58
174,PRT,Portugal,Europe,Southern Europe,91982.0,1143.0,9997600,75.8,105954.0,102133.0,Portugal,Republic,Jorge Sampãio,2914.0,PT,Si,10597.94,108.69
180,ROM,Romania,Europe,Eastern Europe,238391.0,1878.0,22455500,69.9,38158.0,34843.0,România,Republic,Ion Iliescu,3018.0,RO,Si,1699.27,94.20
198,SVK,Slovakia,Europe,Eastern Europe,49012.0,1993.0,5398700,73.7,20594.0,19452.0,Slovensko,Republic,Rudolf Schuster,3209.0,SK,Si,3814.62,110.15
199,SVN,Slovenia,Europe,Southern Europe,20256.0,1991.0,1987800,74.9,19756.0,18202.0,Slovenija,Republic,Milan Kucan,3212.0,SI,Si,9938.63,98.13

In [77]:
df_country2[(df_country2['Crecimiento_económico']== 'Si') & (df_country2['Continent']== 'Europe')].count()

Code                     30
Name                     30
Continent                30
Region                   30
SurfaceArea              30
IndepYear                30
Population               30
LifeExpectancy           30
GNP                      30
GNPOld                   30
LocalName                30
GovernmentForm           30
HeadOfState              30
Capital                  30
Code2                    30
Crecimiento_económico    30
GNP_per_cápita           30
Densidad_poblacional     30
dtype: int64

In [78]:
df_country2[(df_country2['Crecimiento_económico']== 'Si') & (df_country2['Continent']== 'America')] ## Paises con crecimiento economico en America

,Code,Name,Continent,Region,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2,Crecimiento_económico,GNP_per_cápita,Densidad_poblacional
0,ABW,Aruba,America,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Beatrix,129.0,AW,Si,8038.83,533.68
8,ARG,Argentina,America,South America,2780400.0,1816.0,37032000,75.1,340238.0,323310.0,Argentina,Federal Republic,Fernando de la Rúa,69.0,AR,Si,9187.68,13.32
13,ATG,Antigua and Barbuda,America,Caribbean,442.0,1981.0,68000,70.5,612.0,584.0,Antigua and Barbuda,Constitutional Monarchy,Elisabeth II,63.0,AG,Si,9000.00,153.85
24,BHS,Bahamas,America,Caribbean,13878.0,1973.0,307000,71.1,3527.0,3347.0,The Bahamas,Constitutional Monarchy,Elisabeth II,148.0,BS,Si,11488.60,22.12
27,BLZ,Belize,America,Central America,22696.0,1981.0,241000,70.9,630.0,616.0,Belize,Constitutional Monarchy,Elisabeth II,185.0,BZ,Si,2614.11,10.62
28,BMU,Bermuda,America,North America,53.0,NaN,65000,76.9,2328.0,2190.0,Bermuda,Dependent Territory of the UK,Elisabeth II,191.0,BM,Si,35815.38,1226.42
29,BOL,Bolivia,America,South America,1098581.0,1825.0,8329000,63.7,8571.0,7967.0,Bolivia,Republic,Hugo Bánzer Suárez,194.0,BO,Si,1029.06,7.58
31,BRB,Barbados,America,Caribbean,430.0,1966.0,270000,73.0,2223.0,2186.0,Barbados,Constitutional Monarchy,Elisabeth II,174.0,BB,Si,8233.33,627.91
50,CRI,Costa Rica,America,Central America,51100.0,1821.0,4023000,75.8,10226.0,9757.0,Costa Rica,Republic,Miguel Ángel Rodríguez Echeverría,584.0,CR,Si,2541.88,78.73
53,CYM,Cayman Islands,America,Caribbean,264.0,NaN,38000,78.9,1263.0,1186.0,Cayman Islands,Dependent Territory of the UK,Elisabeth II,553.0,KY,Si,33236.84,143.94
58,DMA,Dominica,America,Caribbean,751.0,1978.0,71000,73.4,256.0,243.0,Dominica,Republic,Vernon Shaw,586.0,DM,Si,3605.63,94.54
60,DOM,Dominican Republic,America,Caribbean,48511.0,1844.0,8495000,73.2,15846.0,15076.0,República Dominicana,Republic,Hipólito Mejía Domínguez,587.0,DO,Si,1865.33,175.11
62,ECU,Ecuador,America,South America,283561.0,1822.0,12646000,71.1,19770.0,19769.0,Ecuador,Republic,Gustavo Noboa Bejarano,594.0,EC,Si,1563.34,44.60
88,GTM,Guatemala,America,Central America,108889.0,1821.0,11385000,66.2,19008.0,17797.0,Guatemala,Republic,Alfonso Portillo Cabrera,922.0,GT,Si,1669.57,104.56
94,HND,Honduras,America,Central America,112088.0,1838.0,6485000,69.9,5333.0,4697.0,Honduras,Republic,Carlos Roberto Flores Facussé,933.0,HN,Si,822.36,57.86
96,HTI,Haiti,America,Caribbean,27750.0,1804.0,8222000,49.2,3459.0,3107.0,Haïti/Dayti,Republic,Jean-Bertrand Aristide,929.0,HT,Si,420.70,296.29
107,JAM,Jamaica,America,Caribbean,10990.0,1962.0,2583000,75.2,6871.0,6722.0,Jamaica,Constitutional Monarchy,Elisabeth II,1530.0,JM,Si,2660.09,235.03
135,MEX,Mexico,America,Central America,1958201.0,1810.0,98881000,71.5,414972.0,401461.0,México,Federal Republic,Vicente Fox Quesada,2515.0,MX,Si,4196.68,50.50
146,MTQ,Martinique,America,Caribbean,1102.0,NaN,395000,78.3,2731.0,2559.0,Martinique,Overseas Department of France,Jacques Chirac,2508.0,MQ,Si,6913.92,358.44
165,PAN,Panama,America,Central America,75517.0,1903.0,2856000,75.5,9131.0,8700.0,Panamá,Republic,Mireya Elisa Moscoso Rodríguez,2882.0,PA,Si,3197.13,37.82
172,PRI,Puerto Rico,America,Caribbean,8875.0,NaN,3869000,75.6,34100.0,32100.0,Puerto Rico,Commonwealth of the US,George W. Bush,2919.0,PR,Si,8813.65,435.94
192,SLV,El Salvador,America,Central America,21041.0,1841.0,6276000,69.7,11863.0,11203.0,El Salvador,Republic,Francisco Guillermo Flores Pérez,645.0,SV,Si,1890.22,298.27
197,SUR,Suriname,America,South America,163265.0,1975.0,417000,71.4,870.0,706.0,Suriname,Republic,Ronald Venetiaan,3243.0,SR,Si,2086.33,2.55
213,TTO,Trinidad and Tobago,America,Caribbean,5130.0,1962.0,1295000,68.0,6232.0,5867.0,Trinidad and Tobago,Republic,Arthur N. R. Robinson,3336.0,TT,Si,4812.36,252.44
222,URY,Uruguay,America,South America,175016.0,1828.0,3337000,75.2,20831.0,19967.0,Uruguay,Republic,Jorge Batlle Ibáñez,3492.0,UY,Si,6242.43,19.07
223,USA,United States,America,North America,9363520.0,1776.0,278357000,77.1,8510700.0,8110900.0,United States,Federal Republic,George W. Bush,3813.0,US,Si,30574.77,29.73
227,VEN,Venezuela,America,South America,912050.0,1811.0,24170000,73.1,95023.0,88434.0,Venezuela,Federal Republic,Hugo Chávez Frías,3539.0,VE,Si,3931.44,26.50
228,VGB,"Virgin Islands, British",America,Caribbean,151.0,NaN,21000,75.4,612.0,573.0,British Virgin Islands,Dependent Territory of the UK,Elisabeth II,537.0,VG,Si,29142.86,139.07

In [79]:
df_country2[(df_country2['Crecimiento_económico']== 'Si') & (df_country2['Continent']== 'America')].count()

Code                     28
Name                     28
Continent                28
Region                   28
SurfaceArea              28
IndepYear                22
Population               28
LifeExpectancy           28
GNP                      28
GNPOld                   28
LocalName                28
GovernmentForm           28
HeadOfState              28
Capital                  28
Code2                    28
Crecimiento_económico    28
GNP_per_cápita           28
Densidad_poblacional     28
dtype: int64

In [80]:
df_country2

,Code,Name,Continent,Region,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2,Crecimiento_económico,GNP_per_cápita,Densidad_poblacional
0,ABW,Aruba,America,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Beatrix,129.0,AW,Si,8038.83,533.68
1,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,5976.0,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF,No,263.03,34.84
2,AGO,Angola,Africa,Central Africa,1246700.0,1975.0,12878000,38.3,6648.0,7984.0,Angola,Republic,José Eduardo dos Santos,56.0,AO,No,516.23,10.33
3,AIA,Anguilla,America,Caribbean,96.0,NaN,8000,76.1,63.2,63.2,Anguilla,Dependent Territory of the UK,Elisabeth II,62.0,AI,No,7900.00,83.33
4,ALB,Albania,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqipëria,Republic,Rexhep Mejdani,34.0,AL,Si,942.31,118.31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,YEM,Yemen,Asia,Middle East,527968.0,1918.0,18112000,59.8,6041.0,5729.0,Al-Yaman,Republic,Ali Abdallah Salih,1780.0,YE,Si,333.54,34.31
235,YUG,Yugoslavia,Europe,Southern Europe,102173.0,1918.0,10640000,72.4,17000.0,17000.0,Jugoslavija,Federal Republic,Vojislav Koštunica,1792.0,YU,No,1597.74,104.14
236,ZAF,South Africa,Africa,Southern Africa,1221037.0,1910.0,40377000,51.1,116729.0,129092.0,South Africa,Republic,Thabo Mbeki,716.0,ZA,No,2890.98,33.07
237,ZMB,Zambia,Africa,Eastern Africa,752618.0,1964.0,9169000,37.2,3377.0,3922.0,Zambia,Republic,Frederick Chiluba,3162.0,ZM,No,368.31,12.18
238,ZWE,Zimbabwe,Africa,Eastern Africa,390757.0,1980.0,11669000,37.8,5951.0,8670.0,Zimbabwe,Republic,Robert G. Mugabe,4068.0,ZW,No,509.98,29.86

In [81]:
df_country2['GNP_per_cápita'].mean().round(2) ## GNP per cápita promedio mundial

np.float64(6089.69)

In [82]:
df_country2.groupby('Continent')['GNP_per_cápita'].mean().sort_values(ascending=False) ## GNP per cápita promedio por continente

Continent
Europe        13497.531957
America        6564.192549
Asia           5533.341765
Oceania        3818.794074
Africa         1260.330877
Antarctica             NaN
Name: GNP_per_cápita, dtype: float64

#### Unión de dataframes

In [83]:
df_country3 = df_country2.merge(df_city, left_on='Capital', right_on='ID', how='left') ## Uno df_country2 y df_city por un left join

In [84]:
df_country3

,Code,Name_x,Continent,Region,SurfaceArea,IndepYear,Population_x,LifeExpectancy,GNP,GNPOld,...,Capital,Code2,Crecimiento_económico,GNP_per_cápita,Densidad_poblacional,ID,Name_y,CountryCode,District,Population_y
0,ABW,Aruba,America,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,...,129.0,AW,Si,8038.83,533.68,129.0,Oranjestad,ABW,–,29034.0
1,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,5976.0,...,1.0,AF,No,263.03,34.84,1.0,Kabul,AFG,Kabol,1780000.0
2,AGO,Angola,Africa,Central Africa,1246700.0,1975.0,12878000,38.3,6648.0,7984.0,...,56.0,AO,No,516.23,10.33,56.0,Luanda,AGO,Luanda,2022000.0
3,AIA,Anguilla,America,Caribbean,96.0,NaN,8000,76.1,63.2,63.2,...,62.0,AI,No,7900.00,83.33,62.0,The Valley,AIA,–,595.0
4,ALB,Albania,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,...,34.0,AL,Si,942.31,118.31,34.0,Tirana,ALB,Tirana,270000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,YEM,Yemen,Asia,Middle East,527968.0,1918.0,18112000,59.8,6041.0,5729.0,...,1780.0,YE,Si,333.54,34.31,1780.0,Sanaa,YEM,Sanaa,503600.0
235,YUG,Yugoslavia,Europe,Southern Europe,102173.0,1918.0,10640000,72.4,17000.0,17000.0,...,1792.0,YU,No,1597.74,104.14,1792.0,Beograd,YUG,Central Serbia,1204000.0
236,ZAF,South Africa,Africa,Southern Africa,1221037.0,1910.0,40377000,51.1,116729.0,129092.0,...,716.0,ZA,No,2890.98,33.07,716.0,Pretoria,ZAF,Gauteng,658630.0
237,ZMB,Zambia,Africa,Eastern Africa,752618.0,1964.0,9169000,37.2,3377.0,3922.0,...,3162.0,ZM,No,368.31,12.18,3162.0,Lusaka,ZMB,Lusaka,1317000.0
238,ZWE,Zimbabwe,Africa,Eastern Africa,390757.0,1980.0,11669000,37.8,5951.0,8670.0,...,4068.0,ZW,No,509.98,29.86,4068.0,Harare,ZWE,Harare,1410000.0

In [85]:
df_IsOfficial= df_cl[df_cl['IsOfficial'] == 'T']

In [86]:
df_IsOfficial

    CountryCode   Language IsOfficial  Percentage
0           ABW      Dutch          T         5.3
5           AFG       Dari          T        32.1
6           AFG     Pashto          T        52.4
18          AIA    English          T         0.0
19          ALB  Albaniana          T        97.9
..          ...        ...        ...         ...
963         ZAF  Afrikaans          T        14.3
964         ZAF    English          T         8.5
972         ZAF      Xhosa          T        17.7
973         ZAF       Zulu          T        22.7
980         ZWE    English          T         2.2

[238 rows x 4 columns]

In [87]:
df_final = df_country3.merge(df_IsOfficial, left_on='Code', right_on='CountryCode', how='left')

In [88]:
df_final

,Code,Name_x,Continent,Region,SurfaceArea,IndepYear,Population_x,LifeExpectancy,GNP,GNPOld,...,Densidad_poblacional,ID,Name_y,CountryCode_x,District,Population_y,CountryCode_y,Language,IsOfficial,Percentage
0,ABW,Aruba,America,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,...,533.68,129.0,Oranjestad,ABW,–,29034.0,ABW,Dutch,T,5.3
1,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,5976.0,...,34.84,1.0,Kabul,AFG,Kabol,1780000.0,AFG,Dari,T,32.1
2,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,5976.0,...,34.84,1.0,Kabul,AFG,Kabol,1780000.0,AFG,Pashto,T,52.4
3,AGO,Angola,Africa,Central Africa,1246700.0,1975.0,12878000,38.3,6648.0,7984.0,...,10.33,56.0,Luanda,AGO,Luanda,2022000.0,NaN,NaN,NaN,NaN
4,AIA,Anguilla,America,Caribbean,96.0,NaN,8000,76.1,63.2,63.2,...,83.33,62.0,The Valley,AIA,–,595.0,AIA,English,T,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282,ZAF,South Africa,Africa,Southern Africa,1221037.0,1910.0,40377000,51.1,116729.0,129092.0,...,33.07,716.0,Pretoria,ZAF,Gauteng,658630.0,ZAF,English,T,8.5
283,ZAF,South Africa,Africa,Southern Africa,1221037.0,1910.0,40377000,51.1,116729.0,129092.0,...,33.07,716.0,Pretoria,ZAF,Gauteng,658630.0,ZAF,Xhosa,T,17.7
284,ZAF,South Africa,Africa,Southern Africa,1221037.0,1910.0,40377000,51.1,116729.0,129092.0,...,33.07,716.0,Pretoria,ZAF,Gauteng,658630.0,ZAF,Zulu,T,22.7
285,ZMB,Zambia,Africa,Eastern Africa,752618.0,1964.0,9169000,37.2,3377.0,3922.0,...,12.18,3162.0,Lusaka,ZMB,Lusaka,1317000.0,NaN,NaN,NaN,NaN
286,ZWE,Zimbabwe,Africa,Eastern Africa,390757.0,1980.0,11669000,37.8,5951.0,8670.0,...,29.86,4068.0,Harare,ZWE,Harare,1410000.0,ZWE,English,T,2.2

In [89]:
df_final.drop(columns=['CountryCode_x', 'CountryCode_y','Capital'], inplace=True)

In [90]:
df_final.drop(columns=['Capital'], inplace=True)

KeyError: "['Capital'] not found in axis"

In [91]:
df_final= df_final.rename(columns={'Name_x': 'Country', 'Population_x': 'Population_country', 'Name_y': 'Capital_city', 'Population_y': 'Population_capital'})

In [92]:
df_final['Percentage'] = pd.to_numeric(df_final['Percentage'], errors='coerce') ## Corroborar que Porcentage sea númerico

In [93]:
df_final = df_final.sort_values(by=['Country', 'Percentage'], ascending=[True, False]) ##Ordenar df por country y percentage

In [94]:
df_final2 = df_final.drop_duplicates(subset=['Country'], keep='first') ## Me quedo solo con las filas de country unicas con su capital y principal language

In [95]:
df_final2

,Code,Country,Continent,Region,SurfaceArea,IndepYear,Population_country,LifeExpectancy,GNP,GNPOld,...,Crecimiento_económico,GNP_per_cápita,Densidad_poblacional,ID,Capital_city,District,Population_capital,Language,IsOfficial,Percentage
2,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,5976.0,...,No,263.03,34.84,1.0,Kabul,Kabol,1780000.0,Pashto,T,52.4
5,ALB,Albania,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,...,Si,942.31,118.31,34.0,Tirana,Tirana,270000.0,Albaniana,T,97.9
75,DZA,Algeria,Africa,Northern Africa,2381741.0,1962.0,31471000,69.7,49982.0,46966.0,...,Si,1588.19,13.21,35.0,Alger,Alger,2168000.0,Arabic,T,86.0
13,ASM,American Samoa,Oceania,Polynesia,199.0,NaN,68000,75.1,334.0,334.0,...,No,4911.76,341.71,54.0,Fagatogo,Tutuila,2323.0,Samoan,T,90.6
6,AND,Andorra,Europe,Southern Europe,468.0,1278.0,78000,83.5,1630.0,1630.0,...,No,20897.44,166.67,55.0,Andorra la Vella,Andorra la Vella,21189.0,Catalan,T,32.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,ESH,Western Sahara,Africa,Northern Africa,266000.0,NaN,293000,49.8,60.0,60.0,...,No,204.78,1.10,2453.0,El-Aaiún,El-Aaiún,169000.0,Arabic,T,100.0
279,YEM,Yemen,Asia,Middle East,527968.0,1918.0,18112000,59.8,6041.0,5729.0,...,Si,333.54,34.31,1780.0,Sanaa,Sanaa,503600.0,Arabic,T,99.6
280,YUG,Yugoslavia,Europe,Southern Europe,102173.0,1918.0,10640000,72.4,17000.0,17000.0,...,No,1597.74,104.14,1792.0,Beograd,Central Serbia,1204000.0,Serbo-Croatian,T,75.2
285,ZMB,Zambia,Africa,Eastern Africa,752618.0,1964.0,9169000,37.2,3377.0,3922.0,...,No,368.31,12.18,3162.0,Lusaka,Lusaka,1317000.0,NaN,NaN,NaN
286,ZWE,Zimbabwe,Africa,Eastern Africa,390757.0,1980.0,11669000,37.8,5951.0,8670.0,...,No,509.98,29.86,4068.0,Harare,Harare,1410000.0,English,T,2.2

In [96]:
fill_na_lan = {
    'Language': 'No Official',
    'IsOfficial': 'F',
    'Percentage': 'Na'}

## Relleno nulos de columnas Language, Is Official y Percentage

In [97]:
df_final2 = df_final2.fillna(value=fill_na_lan)

In [98]:
df_final2

,Code,Country,Continent,Region,SurfaceArea,IndepYear,Population_country,LifeExpectancy,GNP,GNPOld,...,Crecimiento_económico,GNP_per_cápita,Densidad_poblacional,ID,Capital_city,District,Population_capital,Language,IsOfficial,Percentage
2,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,5976.0,...,No,263.03,34.84,1.0,Kabul,Kabol,1780000.0,Pashto,T,52.4
5,ALB,Albania,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,...,Si,942.31,118.31,34.0,Tirana,Tirana,270000.0,Albaniana,T,97.9
75,DZA,Algeria,Africa,Northern Africa,2381741.0,1962.0,31471000,69.7,49982.0,46966.0,...,Si,1588.19,13.21,35.0,Alger,Alger,2168000.0,Arabic,T,86.0
13,ASM,American Samoa,Oceania,Polynesia,199.0,NaN,68000,75.1,334.0,334.0,...,No,4911.76,341.71,54.0,Fagatogo,Tutuila,2323.0,Samoan,T,90.6
6,AND,Andorra,Europe,Southern Europe,468.0,1278.0,78000,83.5,1630.0,1630.0,...,No,20897.44,166.67,55.0,Andorra la Vella,Andorra la Vella,21189.0,Catalan,T,32.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,ESH,Western Sahara,Africa,Northern Africa,266000.0,NaN,293000,49.8,60.0,60.0,...,No,204.78,1.10,2453.0,El-Aaiún,El-Aaiún,169000.0,Arabic,T,100.0
279,YEM,Yemen,Asia,Middle East,527968.0,1918.0,18112000,59.8,6041.0,5729.0,...,Si,333.54,34.31,1780.0,Sanaa,Sanaa,503600.0,Arabic,T,99.6
280,YUG,Yugoslavia,Europe,Southern Europe,102173.0,1918.0,10640000,72.4,17000.0,17000.0,...,No,1597.74,104.14,1792.0,Beograd,Central Serbia,1204000.0,Serbo-Croatian,T,75.2
285,ZMB,Zambia,Africa,Eastern Africa,752618.0,1964.0,9169000,37.2,3377.0,3922.0,...,No,368.31,12.18,3162.0,Lusaka,Lusaka,1317000.0,No Official,F,Na
286,ZWE,Zimbabwe,Africa,Eastern Africa,390757.0,1980.0,11669000,37.8,5951.0,8670.0,...,No,509.98,29.86,4068.0,Harare,Harare,1410000.0,English,T,2.2

#### Clasificacíon de paises y sus tipos de centros

In [99]:
cols_validar = ['Densidad_poblacional', 'LifeExpectancy', 'GNP', 'GNPOld', 'GNP_per_cápita']
df_final2[cols_validar] = df_final2[cols_validar].apply(pd.to_numeric, errors='coerce')

In [100]:
## Condiciones para crear un centro único
condicion_centro_unico = (
    (df_final2['Densidad_poblacional'] > 409.86) &
    (df_final2['LifeExpectancy'] > 66) &
    (df_final2['IsOfficial'] == 'T') &
    (df_final2['Crecimiento_económico'] == 'Si') &
    (df_final2['GNP_per_cápita'] > 6089.69))

## Condición múltiples centros
condicion_multiples = (
    (df_final2['Densidad_poblacional'] > 25) &
    (df_final2['LifeExpectancy'] > 53) & 
    (df_final2['IsOfficial'] == 'T') &
    (df_final2['Crecimiento_económico'] == 'Si') &
    (df_final2['GNP_per_cápita'] > 500))

In [101]:
condiciones = [condicion_centro_unico, condicion_multiples]
resultados = ['Centro Único', 'Múltiples Centros']

In [102]:
df_final2['Recomendacion_Instalacion'] = np.select(
    condiciones, 
    resultados, 
    default='No se recomienda instalación')

In [103]:
df_final2['Recomendacion_Instalacion'].value_counts()

Recomendacion_Instalacion
No se recomienda instalación    170
Múltiples Centros                63
Centro Único                      6
Name: count, dtype: int64

In [104]:
df_final2[(df_final2['Densidad_poblacional'] > 25) &
    (df_final2['LifeExpectancy'] > 53) &
    (df_final2['IsOfficial'] == 'T') &
    (df_final2['GNP'] > df_final2['GNPOld']) &
    (df_final2['GNP_per_cápita'] > 500)]

,Code,Country,Continent,Region,SurfaceArea,IndepYear,Population_country,LifeExpectancy,GNP,GNPOld,...,GNP_per_cápita,Densidad_poblacional,ID,Capital_city,District,Population_capital,Language,IsOfficial,Percentage,Recomendacion_Instalacion
5,ALB,Albania,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,...,942.31,118.31,34.0,Tirana,Tirana,270000.0,Albaniana,T,97.9,Múltiples Centros
16,ATG,Antigua and Barbuda,America,Caribbean,442.0,1981.0,68000,70.5,612.0,584.0,...,9000.00,153.85,63.0,Saint John´s,St John,24000.0,English,T,0.0,Múltiples Centros
11,ARM,Armenia,Asia,Middle East,29800.0,1991.0,3520000,66.4,1813.0,1627.0,...,515.06,118.12,126.0,Yerevan,Yerevan,1248700.0,Armenian,T,93.4,Múltiples Centros
0,ABW,Aruba,America,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,...,8038.83,533.68,129.0,Oranjestad,–,29034.0,Dutch,T,5.3,Centro Único
18,AUT,Austria,Europe,Western Europe,83859.0,1918.0,8091800,77.7,211860.0,206025.0,...,26182.06,96.49,1523.0,Wien,Wien,1608144.0,German,T,92.0,Múltiples Centros
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9,ARE,United Arab Emirates,Asia,Middle East,83600.0,1971.0,2441000,74.1,37966.0,36846.0,...,15553.46,29.20,65.0,Abu Dhabi,Abu Dhabi,398695.0,Arabic,T,42.0,Múltiples Centros
92,GBR,United Kingdom,Europe,British Islands,242900.0,1066.0,59623400,77.7,1378330.0,1296830.0,...,23117.27,245.46,456.0,London,England,7285000.0,English,T,97.3,Múltiples Centros
265,USA,United States,America,North America,9363520.0,1776.0,278357000,77.1,8510700.0,8110900.0,...,30574.77,29.73,3813.0,Washington,District of Columbia,572059.0,English,T,86.2,Múltiples Centros
269,VEN,Venezuela,America,South America,912050.0,1811.0,24170000,73.1,95023.0,88434.0,...,3931.44,26.50,3539.0,Caracas,Distrito Federal,1975294.0,Spanish,T,96.9,Múltiples Centros
270,VGB,"Virgin Islands, British",America,Caribbean,151.0,NaN,21000,75.4,612.0,573.0,...,29142.86,139.07,537.0,Road Town,Tortola,8000.0,English,T,0.0,Múltiples Centros

In [105]:
df_final2['SurfaceArea'] = df_final2['SurfaceArea'].astype(int)
df_final2['IndepYear'] = pd.to_numeric(df_final2['IndepYear'], errors='coerce')
df_final2['IndepYear'] = df_final2['IndepYear'].astype('Int64')
df_final2['Population_country'] = df_final2['Population_country'].astype(int)
df_final2['ID'] = pd.to_numeric(df_final2['ID'], errors='coerce')
df_final2['ID'] = df_final2['ID'].astype('Int64')
df_final2['LifeExpectancy'] = df_final2['LifeExpectancy'].astype(float) 
df_final2['GNP'] = df_final2['GNP'].astype(float)  
df_final2['GNP_per_cápita'] = df_final2['GNP_per_cápita'].astype(float)
df_final2['Densidad_poblacional'] = df_final2['Densidad_poblacional'].astype(float) 
df_final2['Population_capital'] = pd.to_numeric(df_final2['Population_capital'], errors='coerce')
df_final2['Population_capital'] = df_final2['Population_capital'].astype('Int64')

In [106]:
print(df_final2.dtypes)

Code                          object
Country                       object
Continent                     object
Region                        object
SurfaceArea                    int64
IndepYear                      Int64
Population_country             int64
LifeExpectancy               float64
GNP                          float64
GNPOld                       float64
LocalName                     object
GovernmentForm                object
HeadOfState                   object
Code2                         object
Crecimiento_económico         object
GNP_per_cápita               float64
Densidad_poblacional         float64
ID                             Int64
Capital_city                  object
District                      object
Population_capital             Int64
Language                      object
IsOfficial                    object
Percentage                    object
Recomendacion_Instalacion     object
dtype: object

#### Obtención de archivo df_final2 con clasificación de paises

In [107]:
df_final2

,Code,Country,Continent,Region,SurfaceArea,IndepYear,Population_country,LifeExpectancy,GNP,GNPOld,...,GNP_per_cápita,Densidad_poblacional,ID,Capital_city,District,Population_capital,Language,IsOfficial,Percentage,Recomendacion_Instalacion
2,AFG,Afghanistan,Asia,Southern and Central Asia,652090,1919,22720000,45.9,5976.0,5976.0,...,263.03,34.84,1,Kabul,Kabol,1780000,Pashto,T,52.4,No se recomienda instalación
5,ALB,Albania,Europe,Southern Europe,28748,1912,3401200,71.6,3205.0,2500.0,...,942.31,118.31,34,Tirana,Tirana,270000,Albaniana,T,97.9,Múltiples Centros
75,DZA,Algeria,Africa,Northern Africa,2381741,1962,31471000,69.7,49982.0,46966.0,...,1588.19,13.21,35,Alger,Alger,2168000,Arabic,T,86.0,No se recomienda instalación
13,ASM,American Samoa,Oceania,Polynesia,199,<NA>,68000,75.1,334.0,334.0,...,4911.76,341.71,54,Fagatogo,Tutuila,2323,Samoan,T,90.6,No se recomienda instalación
6,AND,Andorra,Europe,Southern Europe,468,1278,78000,83.5,1630.0,1630.0,...,20897.44,166.67,55,Andorra la Vella,Andorra la Vella,21189,Catalan,T,32.3,No se recomienda instalación
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,ESH,Western Sahara,Africa,Northern Africa,266000,<NA>,293000,49.8,60.0,60.0,...,204.78,1.10,2453,El-Aaiún,El-Aaiún,169000,Arabic,T,100.0,No se recomienda instalación
279,YEM,Yemen,Asia,Middle East,527968,1918,18112000,59.8,6041.0,5729.0,...,333.54,34.31,1780,Sanaa,Sanaa,503600,Arabic,T,99.6,No se recomienda instalación
280,YUG,Yugoslavia,Europe,Southern Europe,102173,1918,10640000,72.4,17000.0,17000.0,...,1597.74,104.14,1792,Beograd,Central Serbia,1204000,Serbo-Croatian,T,75.2,No se recomienda instalación
285,ZMB,Zambia,Africa,Eastern Africa,752618,1964,9169000,37.2,3377.0,3922.0,...,368.31,12.18,3162,Lusaka,Lusaka,1317000,No Official,F,Na,No se recomienda instalación
286,ZWE,Zimbabwe,Africa,Eastern Africa,390757,1980,11669000,37.8,5951.0,8670.0,...,509.98,29.86,4068,Harare,Harare,1410000,English,T,2.2,No se recomienda instalación

In [108]:
df_final2.sort_values(by=['GNP_per_cápita', 'LifeExpectancy', 'Densidad_poblacional'], ascending=[False, False, False], inplace=True)

In [109]:
df_final2.reset_index(drop=True, inplace=True)

In [110]:
df_final2

,Code,Country,Continent,Region,SurfaceArea,IndepYear,Population_country,LifeExpectancy,GNP,GNPOld,...,GNP_per_cápita,Densidad_poblacional,ID,Capital_city,District,Population_capital,Language,IsOfficial,Percentage,Recomendacion_Instalacion
0,LUX,Luxembourg,Europe,Western Europe,2586,1867,435700,77.100000,16321.0,15519.0,...,37459.26,168.48,2452,Luxembourg [Luxemburg/Lëtzebuerg],Luxembourg,80700,Luxembourgish,T,64.4,Múltiples Centros
1,CHE,Switzerland,Europe,Western Europe,41284,1499,7160400,79.600000,264478.0,256092.0,...,36936.20,173.44,3248,Bern,Bern,122700,German,T,63.6,Múltiples Centros
2,BMU,Bermuda,America,North America,53,<NA>,65000,76.900000,2328.0,2190.0,...,35815.38,1226.42,191,Hamilton,Hamilton,1200,English,T,100.0,Centro Único
3,BRN,Brunei,Asia,Southeast Asia,5765,1984,328000,73.600000,11705.0,12460.0,...,35685.98,56.90,538,Bandar Seri Begawan,Brunei and Muara,21484,Malay,T,45.5,No se recomienda instalación
4,LIE,Liechtenstein,Europe,Western Europe,160,1806,32300,78.800000,1119.0,1084.0,...,34643.96,201.88,2446,Vaduz,Vaduz,5043,German,T,89.0,Múltiples Centros
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,IOT,British Indian Ocean Territory,Africa,Eastern Africa,78,<NA>,0,66.486036,0.0,0.0,...,NaN,0.00,<NA>,NaN,NaN,<NA>,No Official,F,Na,No se recomienda instalación
235,ATF,French Southern territories,Antarctica,Antarctica,7780,<NA>,0,66.486036,0.0,0.0,...,NaN,0.00,<NA>,NaN,NaN,<NA>,No Official,F,Na,No se recomienda instalación
236,HMD,Heard Island and McDonald Islands,Antarctica,Antarctica,359,<NA>,0,66.486036,0.0,0.0,...,NaN,0.00,<NA>,NaN,NaN,<NA>,No Official,F,Na,No se recomienda instalación
237,SGS,South Georgia and the South Sandwich Islands,Antarctica,Antarctica,3903,<NA>,0,66.486036,0.0,0.0,...,NaN,0.00,<NA>,NaN,NaN,<NA>,No Official,F,Na,No se recomienda instalación
238,UMI,United States Minor Outlying Islands,Oceania,Micronesia/Caribbean,16,<NA>,0,66.486036,0.0,0.0,...,NaN,0.00,<NA>,NaN,NaN,<NA>,English,T,0.0,No se recomienda instalación

In [111]:
df_final2.to_csv('df_final2.csv',index=False, sep=';', decimal=',', encoding='utf-8-sig')

#### Filtro de top 10 países recomendados para la instalación de centros

In [112]:
df_final2.head(10)

,Code,Country,Continent,Region,SurfaceArea,IndepYear,Population_country,LifeExpectancy,GNP,GNPOld,...,GNP_per_cápita,Densidad_poblacional,ID,Capital_city,District,Population_capital,Language,IsOfficial,Percentage,Recomendacion_Instalacion
0,LUX,Luxembourg,Europe,Western Europe,2586,1867,435700,77.1,16321.0,15519.0,...,37459.26,168.48,2452,Luxembourg [Luxemburg/Lëtzebuerg],Luxembourg,80700,Luxembourgish,T,64.4,Múltiples Centros
1,CHE,Switzerland,Europe,Western Europe,41284,1499,7160400,79.6,264478.0,256092.0,...,36936.20,173.44,3248,Bern,Bern,122700,German,T,63.6,Múltiples Centros
2,BMU,Bermuda,America,North America,53,<NA>,65000,76.9,2328.0,2190.0,...,35815.38,1226.42,191,Hamilton,Hamilton,1200,English,T,100.0,Centro Único
3,BRN,Brunei,Asia,Southeast Asia,5765,1984,328000,73.6,11705.0,12460.0,...,35685.98,56.90,538,Bandar Seri Begawan,Brunei and Muara,21484,Malay,T,45.5,No se recomienda instalación
4,LIE,Liechtenstein,Europe,Western Europe,160,1806,32300,78.8,1119.0,1084.0,...,34643.96,201.88,2446,Vaduz,Vaduz,5043,German,T,89.0,Múltiples Centros
5,CYM,Cayman Islands,America,Caribbean,264,<NA>,38000,78.9,1263.0,1186.0,...,33236.84,143.94,553,George Town,Grand Cayman,19600,English,T,0.0,Múltiples Centros
6,DNK,Denmark,Europe,Nordic Countries,43094,800,5330000,76.5,174099.0,169264.0,...,32663.98,123.68,3315,København,København,495699,Danish,T,93.5,Múltiples Centros
7,NOR,Norway,Europe,Nordic Countries,323877,1905,4478500,78.7,145895.0,153370.0,...,32576.76,13.83,2807,Oslo,Oslo,508726,Norwegian,T,96.6,No se recomienda instalación
8,USA,United States,America,North America,9363520,1776,278357000,77.1,8510700.0,8110900.0,...,30574.77,29.73,3813,Washington,District of Columbia,572059,English,T,86.2,Múltiples Centros
9,JPN,Japan,Asia,Eastern Asia,377829,-660,126714000,80.7,3787042.0,4192638.0,...,29886.53,335.37,1532,Tokyo,Tokyo-to,7980230,Japanese,T,99.1,No se recomienda instalación

#### Descarga de documentos

In [113]:
df_country2.to_csv('df_country2.csv', index=False, encoding='utf-8-sig', sep=',')

In [114]:
df_city.to_csv('df_city.csv', index=False, encoding='utf-8-sig', sep=',')

In [115]:
df_cl.to_csv('df_cl.csv', index=False, encoding='utf-8-sig', sep=',')